// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProtocolConsumer.Data;

#nullable disable

namespace ProtocolConsumer.Migrations
{
    [DbContext(typeof(ProtocoloDbContext))]
    partial class ProtocoloDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.33");

            modelBuilder.Entity("ProtocolConsumer.Models.LogErro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoErro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroProtocolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogErros");
                });

            modelBuilder.Entity("ProtocolConsumer.Models.Protocolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroProtocolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroVia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NumeroProtocolo")
                        .IsUnique()
                        .HasDatabaseName("idx_numero_protocolo");

                    b.HasIndex("Cpf", "NumeroVia")
                        .IsUnique()
                        .HasDatabaseName("idx_cpf_numero_via");

                    b.HasIndex("Rg", "NumeroVia")
                        .IsUnique()
                        .HasDatabaseName("idx_rg_numero_via");

                    b.ToTable("Protocolos");
                });
#pragma warning restore 612, 618
        }
    }
}
